#!/usr/bin/python3
from os import system

VER = "a0.1"

# Username hardcoded, if start_rc would get broken
UserName = "@"

f = open("start_rc.py")
exec(f.read())
del f

while True:
    command = input(UserName + "# ")
    command = command.lower()

    if command == "exit":
        exit()
    if command == "clear":
        system('clear')
    if command == "ver":
        print(VER)
    if command == "help":
        print("""
exit - exit
clear - clear
ver - show VER
help - show this list
""")
    else:
        print(command + " : command not found")
